env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent: [error, 2]
  linebreak-style: [error, unix]
  quotes: [2, single]
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/react-in-jsx-scope: 2
  semi: [error, never]
  strict: [2, never]

